Schema Binding: # List the schema binding of the resources.
  r1: # The name of the resource.
    product: # The name of the resource
      model: product_model # The RDM for the collection.
    vendor:
      fields: # Define the data model manually.
        - id : 'integer'
        - name: 'string'
        - phone: 'string'
        - email: 'string'
        
Module Configuration: # List the configuration fields.
  - editable: 'boolean' # Use boolean for switch.
  - welcome_text: 'string' # Use string for input box.

Module UserSpace Configuration: # List the individual user confiugration fields.
  - sex :
      enum: # Use enum for checkboxes.
        - 'male'
        - 'female'
